export { default as Details } from './details/Details'
export { default as Home } from './home/Home'
export { default as Login } from './login/Login'
export { default as Planner } from './planner/Planner'
export { default as Profile } from './profile/Profile'
export { default as Registration } from './registration/Registration'
export { default as Reminders } from './reminders/Reminders'
export { default as Search } from './search/Search'
