export { default as BodyPartIcon } from './icons/body.svg'
export { default as BookMarkIcon } from './icons/mark.svg'
export { default as CheckedIcon } from './icons/checked.svg'
export { default as EquipmentIcon } from './icons/equipment.svg'
export { default as UncheckedIcon } from './icons/unchecked.svg'
export { default as UnMarkIcon } from './icons/unmark.svg'

export { default as AbsImage } from './images/abs.png'
export { default as ArmImage } from './images/arms.png'
export { default as BackImage } from './images/back.png'
export { default as CardioImage } from './images/cardio.png'
export { default as ChestImage } from './images/chest.png'
export { default as LegImage } from './images/leg.png'
export { default as NeckImage } from './images/neck.png'
export { default as NoImage } from './images/noImage.png'
export { default as ShoulderImage } from './images/shoulder.png'

export { default as DoneLottie } from './lottie/complete.json'
export { default as ErrorLottie } from './lottie/cancel.json'
export { default as ExerciseLottie } from './lottie/exercise.json'
export { default as InfoLottie } from './lottie/info.json'
export { default as NoInternetLottie } from './lottie/noInternet.json'
export { default as WelcomeLottie } from './lottie/welcomeLottie.json'
